apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-application
spec:
  selector:
    matchLabels:
      app: dotnet-application
  template:
    metadata:
      labels:
        app: dotnet-application
      annotations:
        instrumentation.opentelemetry.io/inject-dotnet: "true"
    spec:
      containers:
      - name: dotnet-application
        image: mcr.microsoft.com/dotnet/samples:aspnetapp
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
